#!/bin/bash

echo "Work Board LED Test Script"
echo "This script will send HID commands to cycle through ticker LEDs"
echo ""
echo "To run this test on your host system:"
echo "1. Install dependencies: sudo apt-get install -y libudev-dev libusb-1.0-0-dev"
echo "2. Build: cargo build"
echo "3. Run with sudo: sudo cargo run"
echo ""
echo "The test will:"
echo "- Connect to Work Board via HID"
echo "- Cycle through 36 ticker positions"
echo "- Light up one LED at a time (bright white)"
echo "- Change ticker every 200ms"
echo ""
echo "LED mapping:"
echo "  Row 1 (0-11):  Number keys 1-0,-,="
echo "  Row 2 (12-23): QWERTYUIOP[]"
echo "  Row 3 (24-35): ASDFGHJKL;'"
echo ""